config/routes.rb
Rails.application.routes.draw do
  root to: 'tweets#index'
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  
   devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tweets
  resources :users,only:[:show]
  resources :admins,only:[:show]

 
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user,optional: true
    belongs_to :admin,optional: true
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    def index
        @tweets = Tweet.all 
    end
    def create
        tweet = Tweet.create(admin_id: params[:admin_id],user_id: params[:user_id],text: params[:text])
        tweet.save
        redirect_to '/tweets'
    end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/index.html.erb
<div style = "display:flex;width:100%;">
 <h1 style = "margin:0px;width:60%;">DoubleTweetApp</h1>
 <div style = "margin-top: auto;margin-bottom: auto;width:40%;">
   <% if admin_signed_in? %>
     <%= link_to '管理者ログアウト', destroy_admin_session_path, method: :delete %>
     <a href = "/admins/<%= current_admin.id%>">管理者:Mypage</a>
　 <% elsif user_signed_in?%>
　　 <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
     <a href = "/users/<%= current_user.id%>">Mypage</a>
   <% else %>
     <a href = "/admins/sign_up">Admin:Sign Up</a>
     <a href = "/admins/sign_in">Admin:Login</a>
     <a href = "/users/sign_up">User:Sign Up</a>
     <a href = "/users/sign_in">User: Login</a>
   <% end %>
 </div>
</div>
<div>
 <% if admin_signed_in? %>
   <form action = "/tweets" method = "post">
     <input type = "hidden" name = "admin_id" value = "<%= current_admin.id%>"></input>
     <input type = "text" name = "text"></input>
     <input type = "submit" value = "管理者投稿"></input>
   </form>
 <% elsif user_signed_in?%>
   <form action = "/tweets" method = "post">
    <input type = "hidden" name = "user_id" value = "<%= current_user.id%>"></input>
    <input type = "text" name = "text"></input>
    <input type = "submit" value = "ユーザー投稿"></input>
   </form>
 <% end %>
 
 <div style = "width:100%;">
 <% @tweets.each do |tweet|%>
   <% if tweet.admin_id == nil%>
   <div style = "width:50%;">
    <p><%= tweet.user.name%></p>
    <p><%= tweet.text%></p>
   </div>
   <% else %>
   <div class = "width:50%;">
    <p><%= tweet.admin.name%></p>
    <p><%= tweet.text%></p>
   </div>
   <% end %>
   
 <% end %>
 </div>
</div>